// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: dishes_allergens.sql

package db

import (
	"context"
)

const createDishesAllergens = `-- name: CreateDishesAllergens :exec
INSERT INTO dishes_allergens (dish_id, allergen_id)
VALUES (?, ?)
`

type CreateDishesAllergensParams struct {
	DishID     string `json:"dish_id"`
	AllergenID int32  `json:"allergen_id"`
}

func (q *Queries) CreateDishesAllergens(ctx context.Context, arg CreateDishesAllergensParams) error {
	_, err := q.db.ExecContext(ctx, createDishesAllergens, arg.DishID, arg.AllergenID)
	return err
}
