// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: dish.sql

package db

import (
	"context"
	"strings"
)

const createDish = `-- name: CreateDish :exec
INSERT INTO dishes (id, menu_id, name)
VALUES (
    ?,
    ?,
    ?
  )
`

type CreateDishParams struct {
	ID     string `json:"id"`
	MenuID string `json:"menu_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateDish(ctx context.Context, arg CreateDishParams) error {
	_, err := q.db.ExecContext(ctx, createDish, arg.ID, arg.MenuID, arg.Name)
	return err
}

const getDish = `-- name: GetDish :one
SELECT id, menu_id, name, created_at
FROM dishes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDish(ctx context.Context, id string) (Dish, error) {
	row := q.db.QueryRowContext(ctx, getDish, id)
	var i Dish
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDishByNames = `-- name: GetDishByNames :many
SELECT id, menu_id, name, created_at
FROM dishes
WHERE name IN (/*SLICE:names*/?)
ORDER BY id
LIMIT ? OFFSET ?
`

type GetDishByNamesParams struct {
	Names  []string `json:"names"`
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
}

func (q *Queries) GetDishByNames(ctx context.Context, arg GetDishByNamesParams) ([]Dish, error) {
	query := getDishByNames
	var queryParams []interface{}
	if len(arg.Names) > 0 {
		for _, v := range arg.Names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(arg.Names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dish{}
	for rows.Next() {
		var i Dish
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDishes = `-- name: ListDishes :many
SELECT id, menu_id, name, created_at
FROM dishes
WHERE menu_id = ?
ORDER BY id
`

func (q *Queries) ListDishes(ctx context.Context, menuID string) ([]Dish, error) {
	rows, err := q.db.QueryContext(ctx, listDishes, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dish{}
	for rows.Next() {
		var i Dish
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
