// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: dish.sql

package db

import (
	"context"
)

const createDish = `-- name: CreateDish :exec
INSERT INTO dishes (id, name)
VALUES (?, ?)
`

type CreateDishParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateDish(ctx context.Context, arg CreateDishParams) error {
	_, err := q.db.ExecContext(ctx, createDish, arg.ID, arg.Name)
	return err
}

const getDish = `-- name: GetDish :many
SELECT dishes.id,
  dishes.name,
  md.menu_id AS menu_id
FROM dishes
  INNER JOIN menu_dishes AS md ON dishes.id = md.dish_id
WHERE dishes.id = ?
ORDER BY dishes.id
LIMIT ? OFFSET ?
`

type GetDishParams struct {
	ID     string `json:"id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetDishRow struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	MenuID string `json:"menu_id"`
}

func (q *Queries) GetDish(ctx context.Context, arg GetDishParams) ([]GetDishRow, error) {
	rows, err := q.db.QueryContext(ctx, getDish, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDishRow{}
	for rows.Next() {
		var i GetDishRow
		if err := rows.Scan(&i.ID, &i.Name, &i.MenuID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDishInCity = `-- name: GetDishInCity :many
SELECT dishes.id,
  dishes.name,
  md.menu_id AS menu_id
FROM dishes
  INNER JOIN menu_dishes AS md ON dishes.id = md.dish_id
  INNER JOIN menus AS m ON md.menu_id = m.id
WHERE dishes.id = ?
  AND m.city_code = ?
ORDER BY dishes.id
LIMIT ? OFFSET ?
`

type GetDishInCityParams struct {
	ID       string `json:"id"`
	CityCode int32  `json:"city_code"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type GetDishInCityRow struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	MenuID string `json:"menu_id"`
}

func (q *Queries) GetDishInCity(ctx context.Context, arg GetDishInCityParams) ([]GetDishInCityRow, error) {
	rows, err := q.db.QueryContext(ctx, getDishInCity,
		arg.ID,
		arg.CityCode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDishInCityRow{}
	for rows.Next() {
		var i GetDishInCityRow
		if err := rows.Scan(&i.ID, &i.Name, &i.MenuID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDish = `-- name: ListDish :many
SELECT dishes.id,
  dishes.name
FROM dishes
ORDER BY id
LIMIT ? OFFSET ?
`

type ListDishParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDishRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListDish(ctx context.Context, arg ListDishParams) ([]ListDishRow, error) {
	rows, err := q.db.QueryContext(ctx, listDish, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDishRow{}
	for rows.Next() {
		var i ListDishRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDishByMenuID = `-- name: ListDishByMenuID :many
SELECT dishes.id,
  dishes.name
FROM dishes
WHERE id IN (
    SELECT dish_id
    FROM menu_dishes
    WHERE menu_id = ?
  )
ORDER BY id
`

type ListDishByMenuIDRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListDishByMenuID(ctx context.Context, menuID string) ([]ListDishByMenuIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listDishByMenuID, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDishByMenuIDRow{}
	for rows.Next() {
		var i ListDishByMenuIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDishByName = `-- name: ListDishByName :many
SELECT dishes.id,
  dishes.name
FROM dishes
WHERE name LIKE ?
ORDER BY id
LIMIT ? OFFSET ?
`

type ListDishByNameParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListDishByNameRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListDishByName(ctx context.Context, arg ListDishByNameParams) ([]ListDishByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listDishByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDishByNameRow{}
	for rows.Next() {
		var i ListDishByNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
