// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: menu_dish.sql

package db

import (
	"context"
)

const createMenuDish = `-- name: CreateMenuDish :exec
INSERT INTO menu_dishes (menu_id, dish_id)
VALUES (?, ?)
`

type CreateMenuDishParams struct {
	MenuID string `json:"menu_id"`
	DishID string `json:"dish_id"`
}

func (q *Queries) CreateMenuDish(ctx context.Context, arg CreateMenuDishParams) error {
	_, err := q.db.ExecContext(ctx, createMenuDish, arg.MenuID, arg.DishID)
	return err
}
