// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateDish(ctx context.Context, arg CreateDishParams) error
	CreateMenu(ctx context.Context, arg CreateMenuParams) error
	GetDish(ctx context.Context, id string) (Dish, error)
	GetDishByNames(ctx context.Context, arg GetDishByNamesParams) ([]Dish, error)
	GetMenu(ctx context.Context, id string) (Menu, error)
	GetMenuByOfferedAt(ctx context.Context, offeredAt time.Time) (Menu, error)
	GetMenuWithDishes(ctx context.Context, id string) (GetMenuWithDishesRow, error)
	GetMenuWithDishesByOfferedAt(ctx context.Context, offeredAt time.Time) (GetMenuWithDishesByOfferedAtRow, error)
	ListDishes(ctx context.Context, arg ListDishesParams) ([]Dish, error)
	ListMenuWithDishes(ctx context.Context, arg ListMenuWithDishesParams) ([]ListMenuWithDishesRow, error)
	ListMenuWithDishesByOfferedAt(ctx context.Context, arg ListMenuWithDishesByOfferedAtParams) ([]ListMenuWithDishesByOfferedAtRow, error)
	ListMenus(ctx context.Context, arg ListMenusParams) ([]Menu, error)
	ListMenusByOfferedAt(ctx context.Context, arg ListMenusByOfferedAtParams) ([]Menu, error)
}

var _ Querier = (*Queries)(nil)
