// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateCity(ctx context.Context, arg CreateCityParams) error
	CreateDish(ctx context.Context, arg CreateDishParams) error
	CreateMenu(ctx context.Context, arg CreateMenuParams) error
	CreateMenuDish(ctx context.Context, arg CreateMenuDishParams) error
	GetCity(ctx context.Context, cityCode int32) (City, error)
	GetDish(ctx context.Context, arg GetDishParams) ([]GetDishRow, error)
	GetDishInCity(ctx context.Context, arg GetDishInCityParams) ([]GetDishInCityRow, error)
	GetMenu(ctx context.Context, arg GetMenuParams) (Menu, error)
	GetMenuWithDishes(ctx context.Context, arg GetMenuWithDishesParams) ([]GetMenuWithDishesRow, error)
	ListCities(ctx context.Context, arg ListCitiesParams) ([]City, error)
	ListCitiesByName(ctx context.Context, arg ListCitiesByNameParams) ([]City, error)
	ListCitiesByPrefecture(ctx context.Context, arg ListCitiesByPrefectureParams) ([]City, error)
	ListDish(ctx context.Context, arg ListDishParams) ([]ListDishRow, error)
	ListDishByMenuID(ctx context.Context, menuID string) ([]ListDishByMenuIDRow, error)
	ListDishByName(ctx context.Context, arg ListDishByNameParams) ([]ListDishByNameRow, error)
	ListMenu(ctx context.Context, arg ListMenuParams) ([]Menu, error)
	ListMenuByCity(ctx context.Context, arg ListMenuByCityParams) ([]Menu, error)
	ListMenuInIds(ctx context.Context, arg ListMenuInIdsParams) ([]Menu, error)
	ListMenuWithDishes(ctx context.Context, arg ListMenuWithDishesParams) ([]ListMenuWithDishesRow, error)
	ListMenuWithDishesByCity(ctx context.Context, arg ListMenuWithDishesByCityParams) ([]ListMenuWithDishesByCityRow, error)
	UpdateAvailable(ctx context.Context, cityCode int32) error
}

var _ Querier = (*Queries)(nil)
