// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateMenu(ctx context.Context, arg CreateMenuParams) error
	GetMenu(ctx context.Context, id string) (Menu, error)
	ListMenus(ctx context.Context, arg ListMenusParams) ([]Menu, error)
}

var _ Querier = (*Queries)(nil)
