version: '3.9'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_lunch
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: ops/docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_SOURCE: 'user:password@tcp(mysql:3306)/school_lunch?charset=utf8mb4&parseTime=True&loc=Local'
    entrypoint: ['/app/wait-for.sh', 'mysql:3306', '--', '/app/run.sh']
    command: ['/app/main']
    depends_on:
      - mysql

volumes:
  mysql:
