version: '3.9'
services:
  mysql:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_lunch
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_SOURCE: mysql://user:password@localhost:3306/school_lunch
    entrypoint: ['/app/wait-for.sh', 'mysql:3306', '--', '/app/run.sh']
    command: ['/app/main']
    depends_on:
      - mysql

volumes:
  mysql:
