// Code generated by MockGen. DO NOT EDIT.
// Source: domain/menu_domain.go
//
// Generated by this command:
//
//	mockgen -source domain/menu_domain.go -destination domain/mocks/menu_domain.go -package mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/ogurilab/school-lunch-api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMenuRepository is a mock of MenuRepository interface.
type MockMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMenuRepositoryMockRecorder
}

// MockMenuRepositoryMockRecorder is the mock recorder for MockMenuRepository.
type MockMenuRepositoryMockRecorder struct {
	mock *MockMenuRepository
}

// NewMockMenuRepository creates a new mock instance.
func NewMockMenuRepository(ctrl *gomock.Controller) *MockMenuRepository {
	mock := &MockMenuRepository{ctrl: ctrl}
	mock.recorder = &MockMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuRepository) EXPECT() *MockMenuRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMenuRepository) Create(ctx context.Context, menu *domain.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, menu)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMenuRepositoryMockRecorder) Create(ctx, menu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMenuRepository)(nil).Create), ctx, menu)
}

// Fetch mocks base method.
func (m *MockMenuRepository) Fetch(ctx context.Context, limit, offset int32) ([]*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockMenuRepositoryMockRecorder) Fetch(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockMenuRepository)(nil).Fetch), ctx, limit, offset)
}

// FetchByRangeDate mocks base method.
func (m *MockMenuRepository) FetchByRangeDate(ctx context.Context, start, end time.Time) ([]*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByRangeDate", ctx, start, end)
	ret0, _ := ret[0].([]*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByRangeDate indicates an expected call of FetchByRangeDate.
func (mr *MockMenuRepositoryMockRecorder) FetchByRangeDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByRangeDate", reflect.TypeOf((*MockMenuRepository)(nil).FetchByRangeDate), ctx, start, end)
}

// FetchByRangeDateWithDishes mocks base method.
func (m *MockMenuRepository) FetchByRangeDateWithDishes(ctx context.Context, start, end time.Time) ([]*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByRangeDateWithDishes", ctx, start, end)
	ret0, _ := ret[0].([]*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByRangeDateWithDishes indicates an expected call of FetchByRangeDateWithDishes.
func (mr *MockMenuRepositoryMockRecorder) FetchByRangeDateWithDishes(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByRangeDateWithDishes", reflect.TypeOf((*MockMenuRepository)(nil).FetchByRangeDateWithDishes), ctx, start, end)
}

// FetchWithDishes mocks base method.
func (m *MockMenuRepository) FetchWithDishes(ctx context.Context, limit, offset int32) ([]*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWithDishes", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWithDishes indicates an expected call of FetchWithDishes.
func (mr *MockMenuRepositoryMockRecorder) FetchWithDishes(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWithDishes", reflect.TypeOf((*MockMenuRepository)(nil).FetchWithDishes), ctx, limit, offset)
}

// GetByDate mocks base method.
func (m *MockMenuRepository) GetByDate(ctx context.Context, offeredAt time.Time) (*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDate", ctx, offeredAt)
	ret0, _ := ret[0].(*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDate indicates an expected call of GetByDate.
func (mr *MockMenuRepositoryMockRecorder) GetByDate(ctx, offeredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDate", reflect.TypeOf((*MockMenuRepository)(nil).GetByDate), ctx, offeredAt)
}

// GetByDateWithDishes mocks base method.
func (m *MockMenuRepository) GetByDateWithDishes(ctx context.Context, offeredAt time.Time) (*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDateWithDishes", ctx, offeredAt)
	ret0, _ := ret[0].(*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateWithDishes indicates an expected call of GetByDateWithDishes.
func (mr *MockMenuRepositoryMockRecorder) GetByDateWithDishes(ctx, offeredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateWithDishes", reflect.TypeOf((*MockMenuRepository)(nil).GetByDateWithDishes), ctx, offeredAt)
}

// GetByID mocks base method.
func (m *MockMenuRepository) GetByID(ctx context.Context, id string) (*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMenuRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMenuRepository)(nil).GetByID), ctx, id)
}

// GetByIDWithDishes mocks base method.
func (m *MockMenuRepository) GetByIDWithDishes(ctx context.Context, id string) (*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithDishes", ctx, id)
	ret0, _ := ret[0].(*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithDishes indicates an expected call of GetByIDWithDishes.
func (mr *MockMenuRepositoryMockRecorder) GetByIDWithDishes(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithDishes", reflect.TypeOf((*MockMenuRepository)(nil).GetByIDWithDishes), ctx, id)
}

// MockMenuUsecase is a mock of MenuUsecase interface.
type MockMenuUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMenuUsecaseMockRecorder
}

// MockMenuUsecaseMockRecorder is the mock recorder for MockMenuUsecase.
type MockMenuUsecaseMockRecorder struct {
	mock *MockMenuUsecase
}

// NewMockMenuUsecase creates a new mock instance.
func NewMockMenuUsecase(ctrl *gomock.Controller) *MockMenuUsecase {
	mock := &MockMenuUsecase{ctrl: ctrl}
	mock.recorder = &MockMenuUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuUsecase) EXPECT() *MockMenuUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMenuUsecase) Create(ctx context.Context, menu *domain.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, menu)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMenuUsecaseMockRecorder) Create(ctx, menu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMenuUsecase)(nil).Create), ctx, menu)
}

// Fetch mocks base method.
func (m *MockMenuUsecase) Fetch(ctx context.Context, limit, offset int32) ([]*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockMenuUsecaseMockRecorder) Fetch(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockMenuUsecase)(nil).Fetch), ctx, limit, offset)
}

// FetchByRangeDate mocks base method.
func (m *MockMenuUsecase) FetchByRangeDate(ctx context.Context, start, end time.Time) ([]*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByRangeDate", ctx, start, end)
	ret0, _ := ret[0].([]*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByRangeDate indicates an expected call of FetchByRangeDate.
func (mr *MockMenuUsecaseMockRecorder) FetchByRangeDate(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByRangeDate", reflect.TypeOf((*MockMenuUsecase)(nil).FetchByRangeDate), ctx, start, end)
}

// FetchByRangeDateWithDishes mocks base method.
func (m *MockMenuUsecase) FetchByRangeDateWithDishes(ctx context.Context, start, end time.Time) ([]*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByRangeDateWithDishes", ctx, start, end)
	ret0, _ := ret[0].([]*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByRangeDateWithDishes indicates an expected call of FetchByRangeDateWithDishes.
func (mr *MockMenuUsecaseMockRecorder) FetchByRangeDateWithDishes(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByRangeDateWithDishes", reflect.TypeOf((*MockMenuUsecase)(nil).FetchByRangeDateWithDishes), ctx, start, end)
}

// FetchWithDishes mocks base method.
func (m *MockMenuUsecase) FetchWithDishes(ctx context.Context, limit, offset int32) ([]*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWithDishes", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWithDishes indicates an expected call of FetchWithDishes.
func (mr *MockMenuUsecaseMockRecorder) FetchWithDishes(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWithDishes", reflect.TypeOf((*MockMenuUsecase)(nil).FetchWithDishes), ctx, limit, offset)
}

// GetByDate mocks base method.
func (m *MockMenuUsecase) GetByDate(ctx context.Context, offeredAt time.Time) (*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDate", ctx, offeredAt)
	ret0, _ := ret[0].(*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDate indicates an expected call of GetByDate.
func (mr *MockMenuUsecaseMockRecorder) GetByDate(ctx, offeredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDate", reflect.TypeOf((*MockMenuUsecase)(nil).GetByDate), ctx, offeredAt)
}

// GetByDateWithDishes mocks base method.
func (m *MockMenuUsecase) GetByDateWithDishes(ctx context.Context, offeredAt time.Time) (*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDateWithDishes", ctx, offeredAt)
	ret0, _ := ret[0].(*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateWithDishes indicates an expected call of GetByDateWithDishes.
func (mr *MockMenuUsecaseMockRecorder) GetByDateWithDishes(ctx, offeredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateWithDishes", reflect.TypeOf((*MockMenuUsecase)(nil).GetByDateWithDishes), ctx, offeredAt)
}

// GetByID mocks base method.
func (m *MockMenuUsecase) GetByID(ctx context.Context, id string) (*domain.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMenuUsecaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMenuUsecase)(nil).GetByID), ctx, id)
}

// GetByIDWithDishes mocks base method.
func (m *MockMenuUsecase) GetByIDWithDishes(ctx context.Context, id string) (*domain.MenuWithDishes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithDishes", ctx, id)
	ret0, _ := ret[0].(*domain.MenuWithDishes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithDishes indicates an expected call of GetByIDWithDishes.
func (mr *MockMenuUsecaseMockRecorder) GetByIDWithDishes(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithDishes", reflect.TypeOf((*MockMenuUsecase)(nil).GetByIDWithDishes), ctx, id)
}
